### ISSUE TITLE
Please add a license file and a readme

### ISSUE THREAD

**Issue by unixorn** [yzdann/kctl#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add plugins with a readme so that users can tell what features they provide.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by yzdann** [comment]
I added license to this project.
Thanks for your feedback!
